"use strict";
var myName = "Rahul";
var myAge = 41;
var canVote = true;
var anything = "SomeValue";
anything = 2;
document.getElementById("tsStuffex1").innerHTML = "first programe </br> My Name is " + myName;
document.write("myname is a " + typeof (myName) + " </br> ");
document.write("myname is a " + typeof (myAge) + " </br> ");
document.write("myname is a " + typeof (canVote) + " </br> ");
var strToNum = parseInt("5");
var numToStr = 5;
document.write(" numTOstring " + numToStr.toString() + " </br>");
document.write(" type of numostr " + typeof (numToStr) + " </br>");
document.write(" type of numostr " + typeof (numToStr.toString()) + " </br>");
